# stage:1
FROM node:22-alpine AS builder
WORKDIR /app
COPY package.json ./
RUN npm install 
COPY . .
RUN npm run build
# stage:2
FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app ./
COPY --from=builder /app/node_modules ./node_modules
RUN npm install 
EXPOSE 3000
CMD ["npm", "start"]
